# Generated by Django 3.2 on 2021-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiangdaitem',
            name='groupname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
